// Generated by gencpp from file sensor_fusion/fusion2lidarGoal.msg
// DO NOT EDIT!


#ifndef SENSOR_FUSION_MESSAGE_FUSION2LIDARGOAL_H
#define SENSOR_FUSION_MESSAGE_FUSION2LIDARGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace sensor_fusion
{
template <class ContainerAllocator>
struct fusion2lidarGoal_
{
  typedef fusion2lidarGoal_<ContainerAllocator> Type;

  fusion2lidarGoal_()
    : points()  {
    }
  fusion2lidarGoal_(const ContainerAllocator& _alloc)
    : points(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::sensor_fusion::fusion2lidarGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensor_fusion::fusion2lidarGoal_<ContainerAllocator> const> ConstPtr;

}; // struct fusion2lidarGoal_

typedef ::sensor_fusion::fusion2lidarGoal_<std::allocator<void> > fusion2lidarGoal;

typedef boost::shared_ptr< ::sensor_fusion::fusion2lidarGoal > fusion2lidarGoalPtr;
typedef boost::shared_ptr< ::sensor_fusion::fusion2lidarGoal const> fusion2lidarGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensor_fusion::fusion2lidarGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensor_fusion::fusion2lidarGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sensor_fusion::fusion2lidarGoal_<ContainerAllocator1> & lhs, const ::sensor_fusion::fusion2lidarGoal_<ContainerAllocator2> & rhs)
{
  return lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sensor_fusion::fusion2lidarGoal_<ContainerAllocator1> & lhs, const ::sensor_fusion::fusion2lidarGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sensor_fusion

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sensor_fusion::fusion2lidarGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_fusion::fusion2lidarGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_fusion::fusion2lidarGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_fusion::fusion2lidarGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_fusion::fusion2lidarGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_fusion::fusion2lidarGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensor_fusion::fusion2lidarGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3fb3f9dacc279b964c4c8341122c34df";
  }

  static const char* value(const ::sensor_fusion::fusion2lidarGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3fb3f9dacc279b96ULL;
  static const uint64_t static_value2 = 0x4c4c8341122c34dfULL;
};

template<class ContainerAllocator>
struct DataType< ::sensor_fusion::fusion2lidarGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_fusion/fusion2lidarGoal";
  }

  static const char* value(const ::sensor_fusion::fusion2lidarGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensor_fusion::fusion2lidarGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Return objects location \n"
"\n"
"# Goal definition\n"
"geometry_msgs/Point[] points\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::sensor_fusion::fusion2lidarGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensor_fusion::fusion2lidarGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct fusion2lidarGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensor_fusion::fusion2lidarGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensor_fusion::fusion2lidarGoal_<ContainerAllocator>& v)
  {
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSOR_FUSION_MESSAGE_FUSION2LIDARGOAL_H
