// Generated by gencpp from file sensor_fusion/ObstacleInfoAction.msg
// DO NOT EDIT!


#ifndef SENSOR_FUSION_MESSAGE_OBSTACLEINFOACTION_H
#define SENSOR_FUSION_MESSAGE_OBSTACLEINFOACTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_fusion/ObstacleInfoActionGoal.h>
#include <sensor_fusion/ObstacleInfoActionResult.h>
#include <sensor_fusion/ObstacleInfoActionFeedback.h>

namespace sensor_fusion
{
template <class ContainerAllocator>
struct ObstacleInfoAction_
{
  typedef ObstacleInfoAction_<ContainerAllocator> Type;

  ObstacleInfoAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  ObstacleInfoAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_fusion::ObstacleInfoActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::sensor_fusion::ObstacleInfoActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::sensor_fusion::ObstacleInfoActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::sensor_fusion::ObstacleInfoAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensor_fusion::ObstacleInfoAction_<ContainerAllocator> const> ConstPtr;

}; // struct ObstacleInfoAction_

typedef ::sensor_fusion::ObstacleInfoAction_<std::allocator<void> > ObstacleInfoAction;

typedef boost::shared_ptr< ::sensor_fusion::ObstacleInfoAction > ObstacleInfoActionPtr;
typedef boost::shared_ptr< ::sensor_fusion::ObstacleInfoAction const> ObstacleInfoActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensor_fusion::ObstacleInfoAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensor_fusion::ObstacleInfoAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sensor_fusion::ObstacleInfoAction_<ContainerAllocator1> & lhs, const ::sensor_fusion::ObstacleInfoAction_<ContainerAllocator2> & rhs)
{
  return lhs.action_goal == rhs.action_goal &&
    lhs.action_result == rhs.action_result &&
    lhs.action_feedback == rhs.action_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sensor_fusion::ObstacleInfoAction_<ContainerAllocator1> & lhs, const ::sensor_fusion::ObstacleInfoAction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sensor_fusion

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sensor_fusion::ObstacleInfoAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_fusion::ObstacleInfoAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_fusion::ObstacleInfoAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_fusion::ObstacleInfoAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_fusion::ObstacleInfoAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_fusion::ObstacleInfoAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensor_fusion::ObstacleInfoAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "23a4d0e7e81259a476ea5c73c0696c95";
  }

  static const char* value(const ::sensor_fusion::ObstacleInfoAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x23a4d0e7e81259a4ULL;
  static const uint64_t static_value2 = 0x76ea5c73c0696c95ULL;
};

template<class ContainerAllocator>
struct DataType< ::sensor_fusion::ObstacleInfoAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_fusion/ObstacleInfoAction";
  }

  static const char* value(const ::sensor_fusion::ObstacleInfoAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensor_fusion::ObstacleInfoAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"ObstacleInfoActionGoal action_goal\n"
"ObstacleInfoActionResult action_result\n"
"ObstacleInfoActionFeedback action_feedback\n"
"\n"
"================================================================================\n"
"MSG: sensor_fusion/ObstacleInfoActionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"ObstacleInfoGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: sensor_fusion/ObstacleInfoGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Return objects location \n"
"\n"
"# Goal definition\n"
"sensor_fusion/ObstacleRanges obstacle_ranges\n"
"\n"
"\n"
"================================================================================\n"
"MSG: sensor_fusion/ObstacleRanges\n"
"ObstacleRange[] obstacle_ranges\n"
"\n"
"================================================================================\n"
"MSG: sensor_fusion/ObstacleRange\n"
"string Class\n"
"float64 xmin\n"
"float64 ymin\n"
"float64 zmin\n"
"float64 xmax\n"
"float64 ymax\n"
"float64 zmax\n"
"geometry_msgs/Point[] points\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: sensor_fusion/ObstacleInfoActionResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"ObstacleInfoResult result\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: sensor_fusion/ObstacleInfoResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Result definition\n"
"sensor_fusion/Obstacles obstacles\n"
"\n"
"\n"
"================================================================================\n"
"MSG: sensor_fusion/Obstacles\n"
"Obstacle[] obstacles\n"
"\n"
"================================================================================\n"
"MSG: sensor_fusion/Obstacle\n"
"string Class\n"
"float64 xCenter\n"
"float64 yCenter\n"
"float64 zCenter\n"
"float64 width\n"
"float64 length\n"
"float64 height\n"
"\n"
"\n"
"================================================================================\n"
"MSG: sensor_fusion/ObstacleInfoActionFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"ObstacleInfoFeedback feedback\n"
"\n"
"================================================================================\n"
"MSG: sensor_fusion/ObstacleInfoFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Feedback definition\n"
"\n"
;
  }

  static const char* value(const ::sensor_fusion::ObstacleInfoAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensor_fusion::ObstacleInfoAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstacleInfoAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensor_fusion::ObstacleInfoAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensor_fusion::ObstacleInfoAction_<ContainerAllocator>& v)
  {
    s << indent << "action_goal: ";
    s << std::endl;
    Printer< ::sensor_fusion::ObstacleInfoActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
    s << std::endl;
    Printer< ::sensor_fusion::ObstacleInfoActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
    s << std::endl;
    Printer< ::sensor_fusion::ObstacleInfoActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSOR_FUSION_MESSAGE_OBSTACLEINFOACTION_H
