// Generated by gencpp from file sensor_fusion/ObstacleInfoResult.msg
// DO NOT EDIT!


#ifndef SENSOR_FUSION_MESSAGE_OBSTACLEINFORESULT_H
#define SENSOR_FUSION_MESSAGE_OBSTACLEINFORESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_fusion/Obstacles.h>

namespace sensor_fusion
{
template <class ContainerAllocator>
struct ObstacleInfoResult_
{
  typedef ObstacleInfoResult_<ContainerAllocator> Type;

  ObstacleInfoResult_()
    : obstacles()  {
    }
  ObstacleInfoResult_(const ContainerAllocator& _alloc)
    : obstacles(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_fusion::Obstacles_<ContainerAllocator>  _obstacles_type;
  _obstacles_type obstacles;





  typedef boost::shared_ptr< ::sensor_fusion::ObstacleInfoResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensor_fusion::ObstacleInfoResult_<ContainerAllocator> const> ConstPtr;

}; // struct ObstacleInfoResult_

typedef ::sensor_fusion::ObstacleInfoResult_<std::allocator<void> > ObstacleInfoResult;

typedef boost::shared_ptr< ::sensor_fusion::ObstacleInfoResult > ObstacleInfoResultPtr;
typedef boost::shared_ptr< ::sensor_fusion::ObstacleInfoResult const> ObstacleInfoResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensor_fusion::ObstacleInfoResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensor_fusion::ObstacleInfoResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sensor_fusion::ObstacleInfoResult_<ContainerAllocator1> & lhs, const ::sensor_fusion::ObstacleInfoResult_<ContainerAllocator2> & rhs)
{
  return lhs.obstacles == rhs.obstacles;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sensor_fusion::ObstacleInfoResult_<ContainerAllocator1> & lhs, const ::sensor_fusion::ObstacleInfoResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sensor_fusion

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sensor_fusion::ObstacleInfoResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_fusion::ObstacleInfoResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_fusion::ObstacleInfoResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_fusion::ObstacleInfoResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_fusion::ObstacleInfoResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_fusion::ObstacleInfoResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensor_fusion::ObstacleInfoResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "12f6f75231b17523dfa33b84d74feebd";
  }

  static const char* value(const ::sensor_fusion::ObstacleInfoResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x12f6f75231b17523ULL;
  static const uint64_t static_value2 = 0xdfa33b84d74feebdULL;
};

template<class ContainerAllocator>
struct DataType< ::sensor_fusion::ObstacleInfoResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_fusion/ObstacleInfoResult";
  }

  static const char* value(const ::sensor_fusion::ObstacleInfoResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensor_fusion::ObstacleInfoResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Result definition\n"
"sensor_fusion/Obstacles obstacles\n"
"\n"
"\n"
"================================================================================\n"
"MSG: sensor_fusion/Obstacles\n"
"Obstacle[] obstacles\n"
"\n"
"================================================================================\n"
"MSG: sensor_fusion/Obstacle\n"
"string Class\n"
"float64 xCenter\n"
"float64 yCenter\n"
"float64 zCenter\n"
"float64 width\n"
"float64 length\n"
"float64 height\n"
"\n"
;
  }

  static const char* value(const ::sensor_fusion::ObstacleInfoResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensor_fusion::ObstacleInfoResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.obstacles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstacleInfoResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensor_fusion::ObstacleInfoResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensor_fusion::ObstacleInfoResult_<ContainerAllocator>& v)
  {
    s << indent << "obstacles: ";
    s << std::endl;
    Printer< ::sensor_fusion::Obstacles_<ContainerAllocator> >::stream(s, indent + "  ", v.obstacles);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSOR_FUSION_MESSAGE_OBSTACLEINFORESULT_H
