// Generated by gencpp from file sensor_fusion/ObstacleInfoGoal.msg
// DO NOT EDIT!


#ifndef SENSOR_FUSION_MESSAGE_OBSTACLEINFOGOAL_H
#define SENSOR_FUSION_MESSAGE_OBSTACLEINFOGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_fusion/ObstacleRanges.h>

namespace sensor_fusion
{
template <class ContainerAllocator>
struct ObstacleInfoGoal_
{
  typedef ObstacleInfoGoal_<ContainerAllocator> Type;

  ObstacleInfoGoal_()
    : obstacle_ranges()  {
    }
  ObstacleInfoGoal_(const ContainerAllocator& _alloc)
    : obstacle_ranges(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_fusion::ObstacleRanges_<ContainerAllocator>  _obstacle_ranges_type;
  _obstacle_ranges_type obstacle_ranges;





  typedef boost::shared_ptr< ::sensor_fusion::ObstacleInfoGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensor_fusion::ObstacleInfoGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ObstacleInfoGoal_

typedef ::sensor_fusion::ObstacleInfoGoal_<std::allocator<void> > ObstacleInfoGoal;

typedef boost::shared_ptr< ::sensor_fusion::ObstacleInfoGoal > ObstacleInfoGoalPtr;
typedef boost::shared_ptr< ::sensor_fusion::ObstacleInfoGoal const> ObstacleInfoGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensor_fusion::ObstacleInfoGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensor_fusion::ObstacleInfoGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sensor_fusion::ObstacleInfoGoal_<ContainerAllocator1> & lhs, const ::sensor_fusion::ObstacleInfoGoal_<ContainerAllocator2> & rhs)
{
  return lhs.obstacle_ranges == rhs.obstacle_ranges;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sensor_fusion::ObstacleInfoGoal_<ContainerAllocator1> & lhs, const ::sensor_fusion::ObstacleInfoGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sensor_fusion

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sensor_fusion::ObstacleInfoGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_fusion::ObstacleInfoGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_fusion::ObstacleInfoGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_fusion::ObstacleInfoGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_fusion::ObstacleInfoGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_fusion::ObstacleInfoGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensor_fusion::ObstacleInfoGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd257e600b199f8f28a59b9f7e1b3dec";
  }

  static const char* value(const ::sensor_fusion::ObstacleInfoGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbd257e600b199f8fULL;
  static const uint64_t static_value2 = 0x28a59b9f7e1b3decULL;
};

template<class ContainerAllocator>
struct DataType< ::sensor_fusion::ObstacleInfoGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_fusion/ObstacleInfoGoal";
  }

  static const char* value(const ::sensor_fusion::ObstacleInfoGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensor_fusion::ObstacleInfoGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Return objects location \n"
"\n"
"# Goal definition\n"
"sensor_fusion/ObstacleRanges obstacle_ranges\n"
"\n"
"\n"
"================================================================================\n"
"MSG: sensor_fusion/ObstacleRanges\n"
"ObstacleRange[] obstacle_ranges\n"
"\n"
"================================================================================\n"
"MSG: sensor_fusion/ObstacleRange\n"
"string Class\n"
"float64 xmin\n"
"float64 ymin\n"
"float64 zmin\n"
"float64 xmax\n"
"float64 ymax\n"
"float64 zmax\n"
"geometry_msgs/Point[] points\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::sensor_fusion::ObstacleInfoGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensor_fusion::ObstacleInfoGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.obstacle_ranges);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstacleInfoGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensor_fusion::ObstacleInfoGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensor_fusion::ObstacleInfoGoal_<ContainerAllocator>& v)
  {
    s << indent << "obstacle_ranges: ";
    s << std::endl;
    Printer< ::sensor_fusion::ObstacleRanges_<ContainerAllocator> >::stream(s, indent + "  ", v.obstacle_ranges);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSOR_FUSION_MESSAGE_OBSTACLEINFOGOAL_H
