// Generated by gencpp from file lidar_obstacle_detector/LidarBBox.msg
// DO NOT EDIT!


#ifndef LIDAR_OBSTACLE_DETECTOR_MESSAGE_LIDARBBOX_H
#define LIDAR_OBSTACLE_DETECTOR_MESSAGE_LIDARBBOX_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace lidar_obstacle_detector
{
template <class ContainerAllocator>
struct LidarBBox_
{
  typedef LidarBBox_<ContainerAllocator> Type;

  LidarBBox_()
    : position()
    , dimension()  {
    }
  LidarBBox_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , dimension(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _dimension_type;
  _dimension_type dimension;





  typedef boost::shared_ptr< ::lidar_obstacle_detector::LidarBBox_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lidar_obstacle_detector::LidarBBox_<ContainerAllocator> const> ConstPtr;

}; // struct LidarBBox_

typedef ::lidar_obstacle_detector::LidarBBox_<std::allocator<void> > LidarBBox;

typedef boost::shared_ptr< ::lidar_obstacle_detector::LidarBBox > LidarBBoxPtr;
typedef boost::shared_ptr< ::lidar_obstacle_detector::LidarBBox const> LidarBBoxConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lidar_obstacle_detector::LidarBBox_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lidar_obstacle_detector::LidarBBox_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lidar_obstacle_detector::LidarBBox_<ContainerAllocator1> & lhs, const ::lidar_obstacle_detector::LidarBBox_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.dimension == rhs.dimension;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lidar_obstacle_detector::LidarBBox_<ContainerAllocator1> & lhs, const ::lidar_obstacle_detector::LidarBBox_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lidar_obstacle_detector

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::lidar_obstacle_detector::LidarBBox_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lidar_obstacle_detector::LidarBBox_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_obstacle_detector::LidarBBox_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_obstacle_detector::LidarBBox_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_obstacle_detector::LidarBBox_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_obstacle_detector::LidarBBox_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lidar_obstacle_detector::LidarBBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5a7abdc1c089cd4f9701ead0a10c7460";
  }

  static const char* value(const ::lidar_obstacle_detector::LidarBBox_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5a7abdc1c089cd4fULL;
  static const uint64_t static_value2 = 0x9701ead0a10c7460ULL;
};

template<class ContainerAllocator>
struct DataType< ::lidar_obstacle_detector::LidarBBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lidar_obstacle_detector/LidarBBox";
  }

  static const char* value(const ::lidar_obstacle_detector::LidarBBox_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lidar_obstacle_detector::LidarBBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point position\n"
"geometry_msgs/Point dimension\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::lidar_obstacle_detector::LidarBBox_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lidar_obstacle_detector::LidarBBox_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.dimension);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LidarBBox_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lidar_obstacle_detector::LidarBBox_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lidar_obstacle_detector::LidarBBox_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "dimension: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.dimension);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIDAR_OBSTACLE_DETECTOR_MESSAGE_LIDARBBOX_H
