// Generated by gencpp from file lidar_obstacle_detector/Obstacles.msg
// DO NOT EDIT!


#ifndef LIDAR_OBSTACLE_DETECTOR_MESSAGE_OBSTACLES_H
#define LIDAR_OBSTACLE_DETECTOR_MESSAGE_OBSTACLES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <lidar_obstacle_detector/Obstacle.h>

namespace lidar_obstacle_detector
{
template <class ContainerAllocator>
struct Obstacles_
{
  typedef Obstacles_<ContainerAllocator> Type;

  Obstacles_()
    : obstacles()  {
    }
  Obstacles_(const ContainerAllocator& _alloc)
    : obstacles(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::lidar_obstacle_detector::Obstacle_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::lidar_obstacle_detector::Obstacle_<ContainerAllocator> >::other >  _obstacles_type;
  _obstacles_type obstacles;





  typedef boost::shared_ptr< ::lidar_obstacle_detector::Obstacles_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lidar_obstacle_detector::Obstacles_<ContainerAllocator> const> ConstPtr;

}; // struct Obstacles_

typedef ::lidar_obstacle_detector::Obstacles_<std::allocator<void> > Obstacles;

typedef boost::shared_ptr< ::lidar_obstacle_detector::Obstacles > ObstaclesPtr;
typedef boost::shared_ptr< ::lidar_obstacle_detector::Obstacles const> ObstaclesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lidar_obstacle_detector::Obstacles_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lidar_obstacle_detector::Obstacles_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lidar_obstacle_detector::Obstacles_<ContainerAllocator1> & lhs, const ::lidar_obstacle_detector::Obstacles_<ContainerAllocator2> & rhs)
{
  return lhs.obstacles == rhs.obstacles;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lidar_obstacle_detector::Obstacles_<ContainerAllocator1> & lhs, const ::lidar_obstacle_detector::Obstacles_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lidar_obstacle_detector

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::lidar_obstacle_detector::Obstacles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lidar_obstacle_detector::Obstacles_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_obstacle_detector::Obstacles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_obstacle_detector::Obstacles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_obstacle_detector::Obstacles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_obstacle_detector::Obstacles_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lidar_obstacle_detector::Obstacles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "75a819090f37b798d8bf3a5f74d98dc8";
  }

  static const char* value(const ::lidar_obstacle_detector::Obstacles_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x75a819090f37b798ULL;
  static const uint64_t static_value2 = 0xd8bf3a5f74d98dc8ULL;
};

template<class ContainerAllocator>
struct DataType< ::lidar_obstacle_detector::Obstacles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lidar_obstacle_detector/Obstacles";
  }

  static const char* value(const ::lidar_obstacle_detector::Obstacles_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lidar_obstacle_detector::Obstacles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Obstacle[] obstacles\n"
"\n"
"================================================================================\n"
"MSG: lidar_obstacle_detector/Obstacle\n"
"string Class\n"
"float64 xCenter\n"
"float64 yCenter\n"
"float64 zCenter\n"
"float64 width\n"
"float64 length\n"
"float64 height\n"
;
  }

  static const char* value(const ::lidar_obstacle_detector::Obstacles_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lidar_obstacle_detector::Obstacles_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.obstacles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Obstacles_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lidar_obstacle_detector::Obstacles_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lidar_obstacle_detector::Obstacles_<ContainerAllocator>& v)
  {
    s << indent << "obstacles[]" << std::endl;
    for (size_t i = 0; i < v.obstacles.size(); ++i)
    {
      s << indent << "  obstacles[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::lidar_obstacle_detector::Obstacle_<ContainerAllocator> >::stream(s, indent + "    ", v.obstacles[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIDAR_OBSTACLE_DETECTOR_MESSAGE_OBSTACLES_H
