(cl:defpackage lidar_obstacle_detector-msg
  (:use )
  (:export
   "<OBSTACLE>"
   "OBSTACLE"
   "<OBSTACLEINFOACTION>"
   "OBSTACLEINFOACTION"
   "<OBSTACLEINFOACTIONFEEDBACK>"
   "OBSTACLEINFOACTIONFEEDBACK"
   "<OBSTACLEINFOACTIONGOAL>"
   "OBSTACLEINFOACTIONGOAL"
   "<OBSTACLEINFOACTIONRESULT>"
   "OBSTACLEINFOACTIONRESULT"
   "<OBSTACLEINFOFEEDBACK>"
   "OBSTACLEINFOFEEDBACK"
   "<OBSTACLEINFOGOAL>"
   "OBSTACLEINFOGOAL"
   "<OBSTACLEINFORESULT>"
   "OBSTACLEINFORESULT"
   "<OBSTACLERANGE>"
   "OBSTACLERANGE"
   "<OBSTACLERANGES>"
   "OBSTACLERANGES"
   "<OBSTACLES>"
   "OBSTACLES"
  ))

