(cl:defpackage lidar_obstacle_detector-msg
  (:use )
  (:export
   "<LIDARBBOX>"
   "LIDARBBOX"
   "<OBSTACLE>"
   "OBSTACLE"
   "<OBSTACLERANGE>"
   "OBSTACLERANGE"
   "<OBSTACLERANGES>"
   "OBSTACLERANGES"
   "<OBSTACLES>"
   "OBSTACLES"
   "<FUSION2LIDARACTION>"
   "FUSION2LIDARACTION"
   "<FUSION2LIDARACTIONFEEDBACK>"
   "FUSION2LIDARACTIONFEEDBACK"
   "<FUSION2LIDARACTIONGOAL>"
   "FUSION2LIDARACTIONGOAL"
   "<FUSION2LIDARACTIONRESULT>"
   "FUSION2LIDARACTIONRESULT"
   "<FUSION2LIDARFEEDBACK>"
   "FUSION2LIDARFEEDBACK"
   "<FUSION2LIDARGOAL>"
   "FUSION2LIDARGOAL"
   "<FUSION2LIDARRESULT>"
   "FUSION2LIDARRESULT"
  ))

