; Auto-generated. Do not edit!


(cl:in-package lidar_obstacle_detector-msg)


;//! \htmlinclude fusion2lidarResult.msg.html

(cl:defclass <fusion2lidarResult> (roslisp-msg-protocol:ros-message)
  ((obstacles
    :reader obstacles
    :initarg :obstacles
    :type lidar_obstacle_detector-msg:Obstacles
    :initform (cl:make-instance 'lidar_obstacle_detector-msg:Obstacles)))
)

(cl:defclass fusion2lidarResult (<fusion2lidarResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <fusion2lidarResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'fusion2lidarResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name lidar_obstacle_detector-msg:<fusion2lidarResult> is deprecated: use lidar_obstacle_detector-msg:fusion2lidarResult instead.")))

(cl:ensure-generic-function 'obstacles-val :lambda-list '(m))
(cl:defmethod obstacles-val ((m <fusion2lidarResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lidar_obstacle_detector-msg:obstacles-val is deprecated.  Use lidar_obstacle_detector-msg:obstacles instead.")
  (obstacles m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <fusion2lidarResult>) ostream)
  "Serializes a message object of type '<fusion2lidarResult>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'obstacles) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <fusion2lidarResult>) istream)
  "Deserializes a message object of type '<fusion2lidarResult>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'obstacles) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<fusion2lidarResult>)))
  "Returns string type for a message object of type '<fusion2lidarResult>"
  "lidar_obstacle_detector/fusion2lidarResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'fusion2lidarResult)))
  "Returns string type for a message object of type 'fusion2lidarResult"
  "lidar_obstacle_detector/fusion2lidarResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<fusion2lidarResult>)))
  "Returns md5sum for a message object of type '<fusion2lidarResult>"
  "12f6f75231b17523dfa33b84d74feebd")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'fusion2lidarResult)))
  "Returns md5sum for a message object of type 'fusion2lidarResult"
  "12f6f75231b17523dfa33b84d74feebd")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<fusion2lidarResult>)))
  "Returns full string definition for message of type '<fusion2lidarResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result definition~%lidar_obstacle_detector/Obstacles obstacles~%~%~%================================================================================~%MSG: lidar_obstacle_detector/Obstacles~%Obstacle[] obstacles~%~%================================================================================~%MSG: lidar_obstacle_detector/Obstacle~%string Class~%float64 xCenter~%float64 yCenter~%float64 zCenter~%float64 width~%float64 length~%float64 height~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'fusion2lidarResult)))
  "Returns full string definition for message of type 'fusion2lidarResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result definition~%lidar_obstacle_detector/Obstacles obstacles~%~%~%================================================================================~%MSG: lidar_obstacle_detector/Obstacles~%Obstacle[] obstacles~%~%================================================================================~%MSG: lidar_obstacle_detector/Obstacle~%string Class~%float64 xCenter~%float64 yCenter~%float64 zCenter~%float64 width~%float64 length~%float64 height~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <fusion2lidarResult>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'obstacles))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <fusion2lidarResult>))
  "Converts a ROS message object to a list"
  (cl:list 'fusion2lidarResult
    (cl:cons ':obstacles (obstacles msg))
))
