; Auto-generated. Do not edit!


(cl:in-package sensor_fusion-msg)


;//! \htmlinclude fusion2lidarResult.msg.html

(cl:defclass <fusion2lidarResult> (roslisp-msg-protocol:ros-message)
  ((lidar_bboxes
    :reader lidar_bboxes
    :initarg :lidar_bboxes
    :type (cl:vector sensor_fusion-msg:LidarBBox)
   :initform (cl:make-array 0 :element-type 'sensor_fusion-msg:LidarBBox :initial-element (cl:make-instance 'sensor_fusion-msg:LidarBBox))))
)

(cl:defclass fusion2lidarResult (<fusion2lidarResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <fusion2lidarResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'fusion2lidarResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name sensor_fusion-msg:<fusion2lidarResult> is deprecated: use sensor_fusion-msg:fusion2lidarResult instead.")))

(cl:ensure-generic-function 'lidar_bboxes-val :lambda-list '(m))
(cl:defmethod lidar_bboxes-val ((m <fusion2lidarResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sensor_fusion-msg:lidar_bboxes-val is deprecated.  Use sensor_fusion-msg:lidar_bboxes instead.")
  (lidar_bboxes m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <fusion2lidarResult>) ostream)
  "Serializes a message object of type '<fusion2lidarResult>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'lidar_bboxes))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'lidar_bboxes))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <fusion2lidarResult>) istream)
  "Deserializes a message object of type '<fusion2lidarResult>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'lidar_bboxes) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'lidar_bboxes)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'sensor_fusion-msg:LidarBBox))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<fusion2lidarResult>)))
  "Returns string type for a message object of type '<fusion2lidarResult>"
  "sensor_fusion/fusion2lidarResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'fusion2lidarResult)))
  "Returns string type for a message object of type 'fusion2lidarResult"
  "sensor_fusion/fusion2lidarResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<fusion2lidarResult>)))
  "Returns md5sum for a message object of type '<fusion2lidarResult>"
  "94e1487bbd7516e1d9285f8a19d02574")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'fusion2lidarResult)))
  "Returns md5sum for a message object of type 'fusion2lidarResult"
  "94e1487bbd7516e1d9285f8a19d02574")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<fusion2lidarResult>)))
  "Returns full string definition for message of type '<fusion2lidarResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result definition~%sensor_fusion/LidarBBox[] lidar_bboxes~%~%~%================================================================================~%MSG: sensor_fusion/LidarBBox~%geometry_msgs/Point point_min~%geometry_msgs/Point point_max~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'fusion2lidarResult)))
  "Returns full string definition for message of type 'fusion2lidarResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result definition~%sensor_fusion/LidarBBox[] lidar_bboxes~%~%~%================================================================================~%MSG: sensor_fusion/LidarBBox~%geometry_msgs/Point point_min~%geometry_msgs/Point point_max~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <fusion2lidarResult>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'lidar_bboxes) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <fusion2lidarResult>))
  "Converts a ROS message object to a list"
  (cl:list 'fusion2lidarResult
    (cl:cons ':lidar_bboxes (lidar_bboxes msg))
))
