; Auto-generated. Do not edit!


(cl:in-package sensor_fusion-msg)


;//! \htmlinclude fusion2yoloFeedback.msg.html

(cl:defclass <fusion2yoloFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass fusion2yoloFeedback (<fusion2yoloFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <fusion2yoloFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'fusion2yoloFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name sensor_fusion-msg:<fusion2yoloFeedback> is deprecated: use sensor_fusion-msg:fusion2yoloFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <fusion2yoloFeedback>) ostream)
  "Serializes a message object of type '<fusion2yoloFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <fusion2yoloFeedback>) istream)
  "Deserializes a message object of type '<fusion2yoloFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<fusion2yoloFeedback>)))
  "Returns string type for a message object of type '<fusion2yoloFeedback>"
  "sensor_fusion/fusion2yoloFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'fusion2yoloFeedback)))
  "Returns string type for a message object of type 'fusion2yoloFeedback"
  "sensor_fusion/fusion2yoloFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<fusion2yoloFeedback>)))
  "Returns md5sum for a message object of type '<fusion2yoloFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'fusion2yoloFeedback)))
  "Returns md5sum for a message object of type 'fusion2yoloFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<fusion2yoloFeedback>)))
  "Returns full string definition for message of type '<fusion2yoloFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback definition~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'fusion2yoloFeedback)))
  "Returns full string definition for message of type 'fusion2yoloFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback definition~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <fusion2yoloFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <fusion2yoloFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'fusion2yoloFeedback
))
