; Auto-generated. Do not edit!


(cl:in-package sensor_fusion-msg)


;//! \htmlinclude ObstacleInfoResult.msg.html

(cl:defclass <ObstacleInfoResult> (roslisp-msg-protocol:ros-message)
  ((obstacles
    :reader obstacles
    :initarg :obstacles
    :type sensor_fusion-msg:Obstacles
    :initform (cl:make-instance 'sensor_fusion-msg:Obstacles)))
)

(cl:defclass ObstacleInfoResult (<ObstacleInfoResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ObstacleInfoResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ObstacleInfoResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name sensor_fusion-msg:<ObstacleInfoResult> is deprecated: use sensor_fusion-msg:ObstacleInfoResult instead.")))

(cl:ensure-generic-function 'obstacles-val :lambda-list '(m))
(cl:defmethod obstacles-val ((m <ObstacleInfoResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sensor_fusion-msg:obstacles-val is deprecated.  Use sensor_fusion-msg:obstacles instead.")
  (obstacles m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ObstacleInfoResult>) ostream)
  "Serializes a message object of type '<ObstacleInfoResult>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'obstacles) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ObstacleInfoResult>) istream)
  "Deserializes a message object of type '<ObstacleInfoResult>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'obstacles) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ObstacleInfoResult>)))
  "Returns string type for a message object of type '<ObstacleInfoResult>"
  "sensor_fusion/ObstacleInfoResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ObstacleInfoResult)))
  "Returns string type for a message object of type 'ObstacleInfoResult"
  "sensor_fusion/ObstacleInfoResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ObstacleInfoResult>)))
  "Returns md5sum for a message object of type '<ObstacleInfoResult>"
  "12f6f75231b17523dfa33b84d74feebd")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ObstacleInfoResult)))
  "Returns md5sum for a message object of type 'ObstacleInfoResult"
  "12f6f75231b17523dfa33b84d74feebd")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ObstacleInfoResult>)))
  "Returns full string definition for message of type '<ObstacleInfoResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result definition~%sensor_fusion/Obstacles obstacles~%~%~%================================================================================~%MSG: sensor_fusion/Obstacles~%Obstacle[] obstacles~%~%================================================================================~%MSG: sensor_fusion/Obstacle~%string Class~%float64 xCenter~%float64 yCenter~%float64 zCenter~%float64 width~%float64 length~%float64 height~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ObstacleInfoResult)))
  "Returns full string definition for message of type 'ObstacleInfoResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result definition~%sensor_fusion/Obstacles obstacles~%~%~%================================================================================~%MSG: sensor_fusion/Obstacles~%Obstacle[] obstacles~%~%================================================================================~%MSG: sensor_fusion/Obstacle~%string Class~%float64 xCenter~%float64 yCenter~%float64 zCenter~%float64 width~%float64 length~%float64 height~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ObstacleInfoResult>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'obstacles))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ObstacleInfoResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ObstacleInfoResult
    (cl:cons ':obstacles (obstacles msg))
))
