; Auto-generated. Do not edit!


(cl:in-package sensor_fusion-msg)


;//! \htmlinclude ObstacleInfoGoal.msg.html

(cl:defclass <ObstacleInfoGoal> (roslisp-msg-protocol:ros-message)
  ((obstacle_ranges
    :reader obstacle_ranges
    :initarg :obstacle_ranges
    :type sensor_fusion-msg:ObstacleRanges
    :initform (cl:make-instance 'sensor_fusion-msg:ObstacleRanges)))
)

(cl:defclass ObstacleInfoGoal (<ObstacleInfoGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ObstacleInfoGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ObstacleInfoGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name sensor_fusion-msg:<ObstacleInfoGoal> is deprecated: use sensor_fusion-msg:ObstacleInfoGoal instead.")))

(cl:ensure-generic-function 'obstacle_ranges-val :lambda-list '(m))
(cl:defmethod obstacle_ranges-val ((m <ObstacleInfoGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sensor_fusion-msg:obstacle_ranges-val is deprecated.  Use sensor_fusion-msg:obstacle_ranges instead.")
  (obstacle_ranges m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ObstacleInfoGoal>) ostream)
  "Serializes a message object of type '<ObstacleInfoGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'obstacle_ranges) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ObstacleInfoGoal>) istream)
  "Deserializes a message object of type '<ObstacleInfoGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'obstacle_ranges) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ObstacleInfoGoal>)))
  "Returns string type for a message object of type '<ObstacleInfoGoal>"
  "sensor_fusion/ObstacleInfoGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ObstacleInfoGoal)))
  "Returns string type for a message object of type 'ObstacleInfoGoal"
  "sensor_fusion/ObstacleInfoGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ObstacleInfoGoal>)))
  "Returns md5sum for a message object of type '<ObstacleInfoGoal>"
  "bd257e600b199f8f28a59b9f7e1b3dec")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ObstacleInfoGoal)))
  "Returns md5sum for a message object of type 'ObstacleInfoGoal"
  "bd257e600b199f8f28a59b9f7e1b3dec")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ObstacleInfoGoal>)))
  "Returns full string definition for message of type '<ObstacleInfoGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Return objects location ~%~%# Goal definition~%sensor_fusion/ObstacleRanges obstacle_ranges~%~%~%================================================================================~%MSG: sensor_fusion/ObstacleRanges~%ObstacleRange[] obstacle_ranges~%~%================================================================================~%MSG: sensor_fusion/ObstacleRange~%string Class~%float64 xmin~%float64 ymin~%float64 zmin~%float64 xmax~%float64 ymax~%float64 zmax~%geometry_msgs/Point[] points~%~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ObstacleInfoGoal)))
  "Returns full string definition for message of type 'ObstacleInfoGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Return objects location ~%~%# Goal definition~%sensor_fusion/ObstacleRanges obstacle_ranges~%~%~%================================================================================~%MSG: sensor_fusion/ObstacleRanges~%ObstacleRange[] obstacle_ranges~%~%================================================================================~%MSG: sensor_fusion/ObstacleRange~%string Class~%float64 xmin~%float64 ymin~%float64 zmin~%float64 xmax~%float64 ymax~%float64 zmax~%geometry_msgs/Point[] points~%~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ObstacleInfoGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'obstacle_ranges))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ObstacleInfoGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ObstacleInfoGoal
    (cl:cons ':obstacle_ranges (obstacle_ranges msg))
))
